name: Build and publish ApiMock

on:
    repository_dispatch:
        types: [release-published]

env:
    DOCKER_HUB_DOMAIN: ${{ secrets.DOCKER_HUB_USER_OPENBANKING }}

    DEFAULT_API_PORT: "7001"
  
jobs:

  build:

    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Checkout openbanking repo
        uses: actions/checkout@v2
        with:
            repository: ${{ github.event.client_payload.repository }}
            ref:  ${{ github.event.client_payload.tagName }}
            path: openbanking        
      
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with: 
          username: ${{ secrets.DOCKER_HUB_USER_OPENBANKING }}
          password: ${{ secrets.DOCKER_HUB_TOKEN_OPENBANKING }}
                
      - uses: docker/setup-buildx-action@v1   
        with:
            buildkitd-flags: --debug      
        
      - uses: actions/setup-node@v1
        with:
          node-version: '12'

      - run: npm install -g @apidevtools/swagger-cli

      - run: swagger-cli bundle openbanking/documentation/source/swagger/parts/_admin_apis_part.yml --outfile openbanking/documentation/source/swagger/swagger_admin_apis.yaml --type=yaml
      - run: swagger-cli bundle openbanking/documentation/source/swagger/parts/_channels_apis_part.yml --outfile openbanking/documentation/source/swagger/swagger_channels_apis.yaml --type=yaml
      - run: swagger-cli bundle openbanking/documentation/source/swagger/parts/_common_apis_part.yml --outfile openbanking/documentation/source/swagger/swagger_common_apis.yaml --type=yaml
      - run: swagger-cli bundle openbanking/documentation/source/swagger/parts/_products_services_apis_part.yml --outfile openbanking/documentation/source/swagger/swagger_products_services_apis.yaml --type=yaml
      - run: swagger-cli bundle openbanking/documentation/source/swagger/parts/_open_banking_apis_part.yml --outfile openbanking/documentation/source/swagger/swagger_open_banking_apis.yml --type=yaml


      - name: Build and push docker image for Open Banking Apis
        id: docker_open_banking_apis
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          tags: ${{ env.DOCKER_HUB_DOMAIN }}/open-banking:${{ github.event.client_payload.tagName }}
          build-args: |
            api_swagger_path=openbanking/documentation/source/swagger/swagger_open_banking_apis.yml
            api_port=${{ env.DEFAULT_API_PORT }}
          push: true
        
      - name: Update version mock in file
        run: |
          echo API_VERSION=${{ github.event.client_payload.tagName }} > .env
          echo DOCKER_HUB_DOMAIN=${DOCKER_HUB_DOMAIN} >> .env 
          git config user.name build-and-publish-mock
          git config user.email build-and-publish-mockgithub.com
          git add .
          git commit -m "Update arquivo .env"
          git push
